# Generated by Django 4.0.6 on 2022-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=180)),
                ('respuesta1', models.CharField(max_length=120)),
                ('respuesta2', models.CharField(max_length=120)),
                ('respuesta3', models.CharField(max_length=120)),
                ('respuesta4', models.CharField(max_length=120)),
            ],
        ),
    ]
