# Generated by Django 4.0.6 on 2022-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.BooleanField()),
                ('no', models.BooleanField()),
            ],
        ),
    ]
