# Generated by Django 4.0.6 on 2022-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='si',
            field=models.IntegerField(),
        ),
    ]
