# Generated by Django 4.0.6 on 2022-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cuestionario_no_alter_cuestionario_si'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='si',
            field=models.IntegerField(null=True),
        ),
    ]
